export default function Head() {
  return (
    <>
      <title>View Snippet</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* Code prettify */}
      {/* <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?skin=sunburst"></script> */}

      {/* <link rel="stylesheet" href="./prettify.css" /> */}
    </>
  );
}
